import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/header/Header';

export const metadata: Metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        {/*<footer>This is a footer</footer>*/}
      </body>
    </html>
  );
}
